### ISSUE TITLE
Inference 5.sparse_calc error in julia

### ISSUE THREAD

**Issue by NanomagLab** [mzjb/DeepH-pack#31]
I'm trying to do the inference step in the "demo_abacus".

```
python calc_OLP_of_CNT.py
deeph-inference --config inference.ini
```

In the inference step, I met an error that I cannot guess why it occur.

Hear in my error:

```
####### Begin 5.sparse_calc
./abacus_CNT.json
[ Info: read h5
Time for reading h5: 2.841439962387085s
[ Info: construct Hamiltonian and overlap matrix in the real space
Time for constructing Hamiltonian and overlap matrix in the real space: 0.7667179107666016 s
[ Info: calculate bands
ERROR: LoadError: PosDefException: matrix is not positive definite; Cholesky factorization failed.
Stacktrace:
 [1] chkposdef
   @ /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/LinearAlgebra/src/lapack.jl:50 [inlined]
 [2] sygvd!(itype::Int64, jobz::Char, uplo::Char, A::Matrix{ComplexF64}, B::Matrix{ComplexF64})
   @ LinearAlgebra.LAPACK /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/LinearAlgebra/src/lapack.jl:5337
 [3] #eigen!#102
   @ /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/LinearAlgebra/src/symmetric.jl:832 [inlined]
 [4] eigen!
   @ /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/LinearAlgebra/src/symmetric.jl:832 [inlined]
 [5] eigen(A::Hermitian{ComplexF64, Matrix{ComplexF64}}, B::Hermitian{ComplexF64, Matrix{ComplexF64}}; kws::Base.Iterators.Pairs{Union{}, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
   @ LinearAlgebra /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/LinearAlgebra/src/eigen.jl:501
 [6] eigen(A::Hermitian{ComplexF64, Matrix{ComplexF64}}, B::Hermitian{ComplexF64, Matrix{ComplexF64}})
   @ LinearAlgebra /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/LinearAlgebra/src/eigen.jl:500
 [7] top-level scope
   @ ~/miniconda3/lib/python3.9/site-packages/deeph/inference/dense_calc.jl:162
in expression starting at /home/whal1235/miniconda3/lib/python3.9/site-packages/deeph/inference/dense_calc.jl:136
Traceback (most recent call last):
  File "/home/whal1235/miniconda3/bin/deeph-inference", line 8, in <module>
    sys.exit(main())
  File "/home/whal1235/miniconda3/lib/python3.9/site-packages/deeph/scripts/inference.py", line 131, in main
    assert capture_output.returncode == 0
AssertionError
```

Note that i did not follow the other steps before.

I used the graphene dataset of the paper. (https://zenodo.org/record/6555484#.ZAseK3ZByUk)

and train a model using "graphene.ini" in the git repository.

I guess the trained model is not a problem because the inference 1-4 processed without any error.

Do you think I should follow the data generation and train step in "demo_abacus"?

Or, is the error occur from another reason?

Thank you.

**Comment by mzjb** [comment]
@NanomagLab 

Hi. I noticed that you used the dataset of out paper, which includes DFT results calculated using the OpenMX code. You should use OpenMX instead of Abacus to compute the overlap matrix.

Alternatively, you can use Abacus to compute the dataset and train the model, and then use your current overlap matrix to calculate the eigenvalues.

I think that your error is due to the mismatch between the Hamiltonian and the overlap matrix.

**Comment by mzjb** [comment]
@NanomagLab 

Hi. I noticed that you used the dataset of our paper, which includes DFT results calculated using the OpenMX code. You should use OpenMX instead of Abacus to compute the overlap matrix.

Alternatively, you can use Abacus to compute the dataset and train the model, and then use your current overlap matrix to calculate the eigenvalues.

I think that your error is due to the mismatch between the Hamiltonian and the overlap matrix.

**Comment by NanomagLab** [comment]
Thank you!!!

**Comment by mzjb** [comment]
I added some information about this dataset to avoid misunderstandings in this [commit](https://github.com/mzjb/DeepH-pack/commit/ff36417b82e1fd8489104a996155386416ad418a).
