### ISSUE TITLE
It can cause band structure instability when using ABACUS' high LCAO base orbitals.

### ISSUE THREAD

**Issue by sgyang345** [mzjb/DeepH-pack#37]
![1x1](https://user-images.githubusercontent.com/68679106/234737714-1d0d2c5c-9894-4141-ab37-8e21dcc13316.png)

**Comment by mzjb** [comment]
Thank you for reporting this issue. The non-physical band structure you calculated may be due to numerical problems caused by the overcompleteness of the basis set, which leads to the singularity of the overlap matrix. As described in the section `A.7. Nearly singular basis sets: Strange results from small-unit-cell periodic
calculation with many k-points` of the FHI-aim documentation, one approach to address this is to compute the eigenvalues of the overlap matrix and project out the corresponding eigenvectors before solving the generalized eigenvalue problem.

We have added this feature to the DeepH diagonalization program in [this commit](https://github.com/mzjb/DeepH-pack/commit/77faf30d9f71438b0e2e21413615c37cce2137f3) to enhance numerical stability. You can use the command-line parameter `ill_project` to determine whether to project out linearly dependent basis functions and `ill_threshold` to set the threshold for eigenvalue magnitudes.

**Comment by sgyang345** [comment]
Thank you very much for your reply, I have been able to get a normal band structure.

![1x1_1](https://user-images.githubusercontent.com/68679106/234849489-79bcd804-9043-41bf-81a4-98237ee4dc79.png)

**Comment by dongsh0320** [comment]
To developer,
I find that this issue was submitted on April 27, 2023, the same day that the answer and code changes were submitted.  The amount of code changes is huge.  Was all this work done in one day?  I am shocked by your quick thinking and work efficiency.
Respect.
